/* Quiet Signal reminder: warm paper, ink, oxide lime, editorial asymmetry, signal rails, calm motion. */
import { Link } from "wouter";
import { ArrowLeft, ArrowUpRight, CheckCircle2, ChevronRight, CircleAlert, Copy, FileCode2, Gauge, LockKeyhole, ShieldAlert, ShieldCheck } from "lucide-react";
import { getSecurityMode } from "@/lib/onyx";

function EvidenceCapture({ title, children, accent = "lime" }: { title: string; children: React.ReactNode; accent?: "lime" | "clay" }) {
  return <div className={`evidence-capture evidence-${accent}`}><div className="evidence-window-bar"><span className="window-dots"><i /><i /><i /></span><span className="evidence-window-title">{title}</span><Copy size={13} /></div><div className="evidence-window-body">{children}</div></div>;
}

export default function Findings() {
  const mode = getSecurityMode();
  return <div className="findings-page">
    <div className="container findings-topline"><Link href="/dashboard" className="back-link"><ArrowLeft size={16} /> Back to workspace</Link><span>OG / ASSESSMENT / FINDINGS</span><div className={`mode-status ${mode}`}><i /> {mode === "vulnerable" ? "VULNERABLE VIEW" : "REMEDIATED VIEW"}</div></div>
    <div className="container findings-hero"><div className="findings-index">08</div><div><p className="eyebrow">Authorized vulnerability assessment</p><h1>Evidence,<br /><em>not alarm.</em></h1><p>Three intentionally selected findings in the Onyx Global simulation, documented with reproducible local evidence and a clear path to remediation.</p></div><div className="findings-summary"><div><strong>03</strong><span>findings</span></div><div><strong>LOCAL</strong><span>scope</span></div><div><strong>FICTIONAL</strong><span>data set</span></div></div></div>
    <div className="container assessment-banner"><ShieldCheck size={18} /><div><strong>Assessment-safe workspace</strong><span>This page documents behavior in the local sandbox only. No real accounts, payment providers, or customer data are involved.</span></div><Link href="/settings">Change mode <ArrowUpRight size={15} /></Link></div>
    <main className="container findings-list">
      <article className="finding-entry"><div className="finding-meta"><span className="finding-number">01</span><span className="finding-code">OG-001</span><span className="finding-area">AUTHENTICATION</span></div><div className="finding-content"><div className="finding-title-row"><div><p className="eyebrow">Insufficient protection against password guessing</p><h2>Repeated guesses<br /><em>remain unchallenged.</em></h2></div><span className="severity-pill severity-medium"><i /> Moderate</span></div><div className="finding-columns"><div className="finding-description"><p>The login API accepts consecutive failed attempts without a rate limiter, progressive delay, CAPTCHA, or account lockout. The local instrumentation counter makes the behavior easy to observe without sending high-volume traffic.</p><div className="finding-facts"><div><span>Endpoint</span><code>POST /api/login</code></div><div><span>Observed state</span><strong>2 failed attempts · 0 blocks</strong></div><div><span>Potential impact</span><strong>Greater exposure to password guessing</strong></div></div><div className="remediation-note"><ShieldCheck size={17} /><span><strong>Recommended remediation</strong><small>Apply layered rate limiting, progressive delays, monitoring, and account-recovery controls at the authentication boundary.</small></span></div></div><EvidenceCapture title="evidence / login-attempts.json"><div className="capture-kicker"><Gauge size={14} /> LOCAL REQUEST TRACE <span>127.0.0.1:3000</span></div><div className="capture-command"><span>$</span> curl -X POST /api/login</div><div className="capture-command muted"><span>$</span> curl -X POST /api/login</div><div className="capture-divider" /><div className="capture-json"><span className="json-key">"error"</span>: <span className="json-string">"Invalid username or password"</span>,<br /><span className="json-key">"finding"</span>: <span className="json-string">"OG-001"</span>,<br /><span className="json-key">"failedAttempts"</span>: <span className="json-number">2</span></div><div className="capture-result"><CircleAlert size={14} /> No throttle response returned</div></EvidenceCapture></div></div></article>
      <article className="finding-entry"><div className="finding-meta"><span className="finding-number">02</span><span className="finding-code">OG-002</span><span className="finding-area">API AUTHORIZATION</span></div><div className="finding-content"><div className="finding-title-row"><div><p className="eyebrow">Broken object level authorization</p><h2>One token,<br /><em>two accounts.</em></h2></div><span className="severity-pill severity-high"><i /> High</span></div><div className="finding-columns"><div className="finding-description"><p>The account endpoint validates that a simulated token exists, but the vulnerable backend intentionally omits an ownership check against the requested account ID. Changing the numeric object ID exposes another fictional customer record.</p><div className="finding-facts"><div><span>Endpoint</span><code>GET /api/account/:id</code></div><div><span>Observed state</span><strong>User 1 token → account 2 returned</strong></div><div><span>Potential impact</span><strong>Unauthorized exposure of account fields</strong></div></div><div className="remediation-note"><ShieldCheck size={17} /><span><strong>Recommended remediation</strong><small>Derive the authenticated subject from the token and enforce an ownership or permission check before returning the object.</small></span></div></div><EvidenceCapture title="evidence / object-access.json" accent="clay"><div className="capture-kicker"><LockKeyhole size={14} /> AUTHORIZED OBJECT TRACE <span>USER ID 1</span></div><div className="capture-command"><span>$</span> GET /api/account/1</div><div className="capture-command"><span>$</span> GET /api/account/2</div><div className="capture-divider" /><div className="capture-json"><span className="json-key">"accessedByUserId"</span>: <span className="json-number">1</span>,<br /><span className="json-key">"account.username"</span>: <span className="json-string">"kwame"</span>,<br /><span className="json-key">"accountNumber"</span>: <span className="json-string">"OG-0002-TEST"</span></div><div className="capture-result capture-result-clay"><ShieldAlert size={14} /> Ownership check not enforced</div></EvidenceCapture></div></div></article>
      <article className="finding-entry"><div className="finding-meta"><span className="finding-number">03</span><span className="finding-code">OG-003</span><span className="finding-area">DATA EXPOSURE</span></div><div className="finding-content"><div className="finding-title-row"><div><p className="eyebrow">Excessive data exposure</p><h2>A profile returns<br /><em>more than it needs.</em></h2></div><span className="severity-pill severity-high"><i /> High</span></div><div className="finding-columns"><div className="finding-description"><p>The profile endpoint returns a full fictional customer object rather than a minimal response for the requested view. The intentionally exposed fields include a password placeholder and internal account classification.</p><div className="finding-facts"><div><span>Endpoint</span><code>GET /api/customer/:id/profile</code></div><div><span>Observed state</span><strong>Password and internal fields returned</strong></div><div><span>Potential impact</span><strong>Unnecessary disclosure of sensitive data</strong></div></div><div className="remediation-note"><ShieldCheck size={17} /><span><strong>Recommended remediation</strong><small>Use endpoint-specific response schemas and return only the fields the client is authorized to display.</small></span></div></div><EvidenceCapture title="evidence / profile-response.json"><div className="capture-kicker"><FileCode2 size={14} /> PROFILE RESPONSE TRACE <span>LOCAL FIXTURE</span></div><div className="capture-command"><span>$</span> GET /api/customer/1/profile</div><div className="capture-divider" /><div className="capture-json"><span className="json-key">"finding"</span>: <span className="json-string">"OG-003"</span>,<br /><span className="json-key">"password"</span>: <span className="json-string">"password123"</span>,<br /><span className="json-key">"internalCustomerType"</span>: <span className="json-string">"STANDARD"</span></div><div className="capture-result"><CircleAlert size={14} /> Response is not minimized</div></EvidenceCapture></div></div></article>
    </main>
    <div className="container findings-footer-row"><Link href="/settings" className="assessment-next"><span><FileCode2 size={17} /> Open security mode settings</span><ArrowUpRight size={16} /></Link><span className="findings-disclaimer">All evidence shown is fictional and generated for local coursework.</span></div>
  </div>;
}
